### ISSUE TITLE
查询信息失败

### ISSUE THREAD

**Issue by zhiluop** [Windylh/nonebot_plugin_apexranklookup#1]
在输入 .查询 后没有输出，到后台看报错Event.get_plaintext() takes 1 positional argument but 2 were given。好像是因为get_plaintext获取的是state类型，删掉后能够正常输出。

ps（提一个小小的建议，把查询做成on_command触发式比较方便。

**Comment by Windylh** [comment]
对的，目前只做了一个.stat/查询+id的处理，没有对不带id的进行catch，一会处理一下

**Comment by Windylh** [comment]
因为查询是后面带origin_id的，on_command的话需要用正则写个处理，startswith更简便。
state类型修复了。

**Comment by zhiluop** [comment]
但是这样的话，如果存在命令前缀prefix，其余三个都需要加上prefix，只有查询不加的话，是不是会让安装插件的别人产生误解，导致错误或者不能使用查询呢？
如果要用startswith的话，建议在命令说明中单独说一下用法作一下区分。

**Comment by Windylh** [comment]
懂了，了解意思了，统一on_command吧（）
