### ISSUE TITLE
输入.stat命令无反应 

### ISSUE THREAD

**Issue by johnsilverhand** [Windylh/nonebot_plugin_apexranklookup#5]
输入.复制器与输入.map命令有反馈
输入.stat命令无反应，控制台输出如下：
11-09 23:15:34 [DEBUG] nonebot | Checking for matchers in priority 1...
11-09 23:15:34 [DEBUG] nonebot | Checking for matchers in priority 5...
11-09 23:15:34 [DEBUG] nonebot | Checking for matchers in priority 10...

**Comment by Windylh** [comment]
请提供一下nonebot启动阶段log

**Comment by johnsilverhand** [comment]
warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
11-09 22:55:24 [SUCCESS] nonebot | NoneBot is initializing...
11-09 22:55:25 [INFO] nonebot | Current Env: dev
11-09 22:55:25 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 41156, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': {''}, 'nickname': {'lazy4', 'bot'}, 'command_start': {'/', '', '.'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'fastapi_reload': True, 'environment': 'dev'}
11-09 22:55:25 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
11-09 22:55:26 [SUCCESS] nonebot | Succeeded to import "echo"
11-09 22:55:26 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_code"
11-09 22:55:28 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
11-09 22:55:28 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_BitTorrent"
11-09 22:55:28 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apexranklookup-master"
11-09 22:55:28 [SUCCESS] nonebot | Running NoneBot...
11-09 22:55:28 [DEBUG] nonebot | Loaded adapters: OneBot V11
11-09 22:55:28 [INFO] uvicorn | Will watch for changes in these directories: ['H:\\nb_lazy4\\lazy4']
11-09 22:55:28 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:41156 (Press CTRL+C to quit)
11-09 22:55:28 [INFO] uvicorn | Started reloader process [28436] using WatchFiles
11-09 22:55:30 [SUCCESS] nonebot | NoneBot is initializing...
11-09 22:55:30 [INFO] nonebot | Current Env: dev
11-09 22:55:30 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 41156, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': {''}, 'nickname': {'lazy4', 'bot'}, 'command_start': {'/', '', '.'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'fastapi_reload': True}
11-09 22:55:30 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
11-09 22:55:30 [SUCCESS] nonebot | Succeeded to import "echo"
11-09 22:55:31 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_code"
11-09 22:55:33 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
11-09 22:55:33 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_BitTorrent"
c:\users\该电脑的使用者\appdata\local\programs\python\python39\lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
11-09 22:55:34 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apexranklookup-master"
11-09 22:55:34 [INFO] uvicorn | Started server process [7388]
11-09 22:55:34 [INFO] uvicorn | Waiting for application startup.
11-09 22:55:35 [WARNING] nonebot_plugin_gocqhttp | Possible duplicate_pid=12496 found, terminated.
11-09 22:55:35 [INFO] nonebot_plugin_gocqhttp | [2243259440] 当前版本:v1.0.0-rc3
11-09 22:55:35 [INFO] nonebot_plugin_gocqhttp | [2243259440] 将使用 device.json 内的设备信息运行Bot.
11-09 22:55:35 [INFO] nonebot_plugin_gocqhttp | [2243259440] 开始尝试登录并同步消息...
11-09 22:55:35 [INFO] nonebot_plugin_gocqhttp | [2243259440] 使用协议: iPad
11-09 22:55:35 [INFO] nonebot_plugin_gocqhttp | [2243259440] Protocol -> connect to server: [::ffff:125.39.196.172]:808011-09 22:55:35 [WARNING] nonebot_plugin_gocqhttp | [2243259440] Protocol -> device lock is disable. http api may fail.
11-09 22:55:37 [INFO] nonebot_plugin_gocqhttp | [2243259440] 登录成功 欢迎使用: Lazy4
11-09 22:55:37 [INFO] nonebot_plugin_gocqhttp | [2243259440] 开始加载好友列表...
11-09 22:55:37 [INFO] nonebot_plugin_gocqhttp | [2243259440] 共加载 3 个好友.
11-09 22:55:37 [INFO] nonebot_plugin_gocqhttp | [2243259440] 开始加载群列表...
11-09 22:55:37 [INFO] nonebot_plugin_gocqhttp | [2243259440] 共加载 0 个群.
11-09 22:55:37 [INFO] nonebot_plugin_gocqhttp | go-cqhttp for 2243259440 has successfully started.
11-09 22:55:37 [INFO] nonebot_plugin_gocqhttp | [2243259440] 资源初始化完成, 开始处理信息.
11-09 22:55:37 [INFO] nonebot_plugin_gocqhttp | [2243259440] アトリは、高性能ですから!
11-09 22:55:37 [INFO] nonebot_plugin_gocqhttp | [2243259440] 正在检查更新.
11-09 22:55:37 [INFO] nonebot_plugin_gocqhttp | [2243259440] 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:41156/onebot/v11/ws
11-09 22:55:38 [INFO] nonebot_plugin_gocqhttp | Startup complete, Web UI has served to http://127.0.0.1:41156/go-cqhttp/11-09 22:55:38 [INFO] uvicorn | Application startup complete.
11-09 22:55:38 [INFO] uvicorn | ('127.0.0.1', 1961) - "WebSocket /onebot/v11/ws" [accepted]
11-09 22:55:38 [INFO] nonebot | OneBot V11 | Bot 2243259440 connected
11-09 22:55:38 [INFO] websockets | connection open
11-09 22:55:38 [INFO] nonebot_plugin_gocqhttp | [2243259440] 已连接到反向WebSocket Universal服务器 ws://127.0.0.1:41156/onebot/v11/ws
11-09 22:55:38 [INFO] nonebot_plugin_gocqhttp | [2243259440] 检查更新完成. 当前已运行最新版本.
11-09 22:55:38 [INFO] nonebot_plugin_gocqhttp | [2243259440] 开始诊断网络情况
11-09 22:55:40 [INFO] nonebot_plugin_gocqhttp | [2243259440] 网络诊断完成. 未发现问题

**Comment by Windylh** [comment]
从log看来没啥问题，可以试试在这个插件handle里输出一下，看看是信息没进到插件还是插件处理的问题。

**Comment by johnsilverhand** [comment]
将__init__.py文件中第19行代码
rank = worker.on_command((".stat", ".查询"))
改为
rank = worker.on_command(".stat", aliases={".查询"})
现在可以正常反馈
现在输出“.stat vangams233”命令 log如下：
11-10 00:27:43 [SUCCESS] nonebot | OneBot V11 2243259440 | [message.private.friend]: Message -1398021697 from 1477981379 ".stat vangams233"
11-10 00:27:43 [DEBUG] nonebot | Checking for matchers in priority 1...
11-10 00:27:43 [DEBUG] nonebot | Checking for matchers in priority 5...
11-10 00:27:43 [DEBUG] nonebot | Checking for matchers in priority 10...
11-10 00:27:43 [INFO] nonebot | Event will be handled by Matcher(type='message', module=lazy4.plugins.nonebot_plugin_apexranklookup-master)
11-10 00:27:43 [DEBUG] nonebot | Running Matcher(type='message', module=lazy4.plugins.nonebot_plugin_apexranklookup-master)
11-10 00:27:43 [DEBUG] nonebot | Running handler Dependent(call=query_rank)
11-10 00:27:43 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
11-10 00:27:43 [INFO] nonebot_plugin_gocqhttp | [2243259440] 发送好友 1477981379(1477981379)  的消息: [{"type":  ... (114998254)
11-10 00:27:49 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
11-10 00:27:50 [INFO] nonebot_plugin_gocqhttp | [2243259440] 发送好友 1477981379(1477981379)  的消息: [{"type":  ... (1910344568)
11-10 00:27:50 [INFO] nonebot | Matcher(type='message', module=lazy4.plugins.nonebot_plugin_apexranklookup-master) running complete
11-10 00:27:50 [DEBUG] nonebot | Stop event propagation
